#!/bin/sh
if [ -z "$1" ]; then
	echo "syntax: $0 ompi|mpich [-k] [--debug]"
	echo "	-k to kill containers"
	echo "	--debug to start containers only (ssh+mpi command will be shown)"
	exit 1
fi
mpi="$1"
shift
./mpirun -host brtestdocker1,brtestdocker2 -dockerimage "test$mpi" -$mpi sendrecv "$@"
