#!/bin/sh

./1-RUNME ompi -k
./1-RUNME mpich -k

set -e

pwd=$(cd ${0%/*}; pwd)
cd $pwd

#### network

netbr1=10.242
netbr2=10.243

docker network remove brtestdocker1 || true; \
docker network create --subnet ${netbr1}.1.0/24 --gateway ${netbr1}.1.1 --label brtestdocker1 --driver bridge -o com.docker.network.bridge.name=brtestdocker1 brtestdocker1 && \
docker network inspect brtestdocker1

docker network remove brtestdocker2 || true; \
docker network create --subnet ${netbr2}.1.0/24 --gateway ${netbr2}.1.1 --label brtestdocker2 --driver bridge -o com.docker.network.bridge.name=brtestdocker2 brtestdocker2 && \
docker network inspect brtestdocker2

#### docker user

if false; then

	# if enabled ("if true" above), systemd will launch docker
	# with the option "--userns-remap=default" meaning that root
	# inside container is not root on host.
	# at the time of writing (16/10/31), there is ala a bug in ubuntu sometimes preventing this
	# to run smoothly: https://github.com/opencontainers/runc/issues/769
	
# using systemd, start docker with root protection on
echo 'DOCKER_OPTS="--userns-remap=default"' > /etc/default/docker
mkdir -p /etc/systemd/system/docker.service.d
cat << EOF > /etc/systemd/system/docker.service.d/noroot.conf
[Service]
EnvironmentFile=-/etc/default/docker
ExecStart=
ExecStart=/usr/bin/dockerd \$DOCKER_OPTS
EOF
systemctl daemon-reload
service docker restart

fi

#### break docker isolation between these two bridges

echo "docker bridge isolation rules:"
echo "----------------------------------------------------"
sudo iptables -L -v --line-numbers|egrep -e "(DROP.*brtestdocker.*brtestdocker|ISOLATION)"
while true; do
	dockerisolationrule=$(sudo iptables -L -v --line-numbers|grep  DROP.*brtestdocker.*brtestdocker|awk '{print $1;}'|head -1)
	test -z "${dockerisolationrule}" && break
	sudo iptables -D DOCKER-ISOLATION ${dockerisolationrule}
done
echo "----------------------------------------------------"
echo "no more isolation:"
echo "----------------------------------------------------"
sudo iptables -L -v --line-numbers|egrep -e "(DROP.*brtestdocker.*brtestdocker|ISOLATION)"
echo "----------------------------------------------------"
